name: foronpape
favicon: null
layout_spectrum: 0.67208
typography_spectrum: 0.05965067376382649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1d1d'
    - '#7a4242'
    - '#c8ac8e'
    - '#b46363'
    - '#e2e9e8'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.6797581221908331
  rhythmicContrast: 0.9519606630783528
purpose: []
